apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identityapi
        image: vivek151189/identityapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__IdentityConnection
          value: "Data Source=mssql;Initial Catalog=IdentityDB;Persist Security Info=True;User ID=sa;Password=Labuser@123456"
        - name: Jwt__secrete
          value: "Thisismylengthysecretkeyforencryption"
        - name: Jwt__Issuer
          value: "http://identitysvc"
        - name: Jwt__Audience
          value: "http://eventsvc"

