apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  selector:
    matchLabels:
      app: sql
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sqlserver2017
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        ports:
        - containerPort: 1433
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
